apiVersion: v1
kind: Service
metadata:
  name: mapd
  labels:
    app: mapd
spec:
  ports:
    - port: 6273
      name: mapd
      protocol: TCP
      targetPort: 6273
  selector:
    app: mapd
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mapd-pv-claim
  labels:
    app: mapd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mapd
  labels:
    app: mapd
spec:
  selector:
    matchLabels:
      app: mapd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mapd
    spec:
      containers:
      - image: docker.io/omnisci/omnisci-ee-cuda:latest
        name: omnisci-ee-cuda
        env:
        - name: NVIDIA_DRIVER_CAPABILITES
          value: compute,utility
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        ports:
        - containerPort: 6273
          name: mapd
        volumeMounts:
        - name: mapd-persistent-storage
          mountPath: /omnisci-storage
      volumes:
      - name: mapd-persistent-storage
        persistentVolumeClaim:
          claimName: mapd-pv-claim
