apiVersion: v1
kind: Service
metadata:
  name: rshiny
  labels:
    app: rshiny
spec:
  ports:
    - port: 8787
      name: rshiny
      protocol: TCP
      targetPort: 8787
  selector:
    app: rshiny
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rshiny-pv-claim
  labels:
    app: rshiny
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rshiny
  labels:
    app: rshiny
spec:
  selector:
    matchLabels:
      app: rshiny
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rshiny
    spec:
      containers:
      - image: quay.io/danclark/r-geospatial:devel
        name: r-geospatial
        env:
        - name: NVIDIA_DRIVER_CAPABILITES
          value: compute,utility
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        ports:
        - containerPort: 8787
          name: rshiny
        volumeMounts:
        - name: rshiny-persistent-storage
          mountPath: /data
      volumes:
      - name: rshiny-persistent-storage
        persistentVolumeClaim:
          claimName: rshiny-pv-claim
